import "./globals.css";
import { Inter } from "next/font/google";
import SupabaseProvider from "./supabase-provider";

export const metadata = {
  title: "Introducty ⚡ The fastest way to put your link in bio",
  description: "Generated by Next.js",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="container">
          <SupabaseProvider session={null}>{children}</SupabaseProvider>
        </main>
      </body>
    </html>
  );
}
